### ISSUE TITLE
ch1/1.2/k8s-min-5GiB/Vagrantfile 에 수정이 필요합니다.

### ISSUE THREAD

**Issue by Shabet** [sysnet4admin/_Lecture_k8s_starter.kit#2]
인증 문제로 설치가 되지 않아서 아래의 내용이 추가가 필요합니다.

cfg.vm.box_download_insecure = true

**Comment by sysnet4admin** [comment]
안녕하세요 

현재 버전인 v1.25.0이 설치되는 과정은 다음의 파일에서 확인할 수 있습니다. 
https://github.com/sysnet4admin/_Lecture_k8s_starter.kit/blob/main/ch1/1.2/k8s-min-5GiB/vagrantup-v1.25.output

또한 Vagrant Box 이미지가 `0.8.0`으로 업데이트 된 이후에도 vagrant up을 시도해 보았으나, 인증 관련한 문제는 확인되지 않습니다. 
<img width="846" alt="image" src="https://github.com/sysnet4admin/_Lecture_k8s_starter.kit/assets/29163931/21eff639-d114-4f67-b522-914074b0b325">

호스트 시스템의 특수한 환경과 관련이 있는지 또한 확인되지 않으므로, 구체적으로 해당 사항을 재현할 수 있는 정보등을 제공해 주시면 
다시 한번 살펴 보도록 하겠습니다.

**Comment by sysnet4admin** [comment]
그리고 랩 관련한 문제는 강의 질문 페이지에 주시는게 좋을 것 같습니다. 
확인되지 않은 문제가 이슈에 쌓이는 건 관리적인 측면에 좋지 않을 것 같다는 의견 드립니다.
